src/cartview/urls.py
from django.urls import path

from . import views
app_name = "cartview"

# Cart Urls

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cartitem_del/<int:pk>/', views.DeleteCartItem.as_view(), name='cartitem_del'),
    path('submit_order/', views.Order.as_view(), name='submit_order'),
    path('submit_success/', views.OrderSuccess.as_view(), name='submit_success'),
    path('my_orders/', views.MyOrders.as_view(), name='my_orders'),
    path('order_upd/<int:pk>/', views.UpdOrder.as_view(), name = 'order_update'),
    #path('cart_item', views.cart_item, name='cart_item'),
    #path('cart_item', views.ViewCartItem.as_view(), name='cart_item'),
    
]

"""
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-list', views.ListCart.as_view(), name='cart_list'),
    path('cart/create/', views.CreateCart.as_view(), name='cart_create'),
    path('cart/<int:pk>/update/', views.UpdateCart.as_view(), name='cart_update'),
    path('cart/<int:pk>/delete/', views.DeleteCart.as_view(), name='cart_delete'),
]

# CartItem Urls
urlpatterns += [
    path('cartitem/', views.cart_item, name='cartitem_view'),
    #path('cartitem/', views.ViewCartItem.as_view(), name='cartitem_view'),
    #path('cartitem/<int:pk>/', views.DetailCartItem.as_view(), name='cartitem_detail'),
    path('cartitem/create/', views.CreateCartItem.as_view(), name='cartitem_create'),
    path('cartitem/<int:pk>/update/', views.UpdateCartItem.as_view(), name='cartitem_update'),
    path('cartitem/<int:pk>/delete/', views.DeleteCartItem.as_view(), name='cartitem_delete'),
]

"""

src/loginpage/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, SignupSuccess
from . import views


app_name = "loginpage"


urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout', auth_views.LoginView.as_view(template_name='loginpage/login.html'), name = 'logout'),
    path('reset-form', auth_views.LoginView.as_view(template_name='loginpage/password_reset_form.html'), name = 'reset-form'),
    path('reset-done', auth_views.LoginView.as_view(template_name='loginpage/password_reset_done.html'), name = 'reset-done'),
    path('reset-confirm', auth_views.LoginView.as_view(template_name='loginpage/password_reset_confirm.html'), name = 'reset-confirm'),
    path('reset-complete', auth_views.LoginView.as_view(template_name='loginpage/password_reset_complete.html'), name = 'reset-complete'),
    path('signup/', SignUpView.as_view(), name="signup"),
    #path('signup_success/', SignupSuccess.as_view(), name='signup_success')
    path('signup_success/', views.SignupSuccess.as_view(), name='signup_success'),

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from reflib import views
from mainpage import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainPage.as_view(), name = 'main'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('reflib/', include('reflib.urls', namespace="reflib")),
    path('bookview/', include('bookview.urls', namespace="bookview")),
    path('profiles/', include('loginpage.urls',namespace="profiles")),
    path('cartview/', include('cartview.urls', namespace="cartview")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cartview/models.py
from django.db import models
from django.contrib.auth import get_user_model
from bookview.models import Book


User = get_user_model()
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="carts", verbose_name="User Cart", null=True,blank=True)
    created_at = models.DateTimeField('Created At',auto_now=False, auto_now_add=True
    )
    
   
    def total_price(self):
        all_items_in_cart = self.bookview.all()
        total_price = 0
        for item_in_cart in all_items_in_cart:
            total_price += item_in_cart.price_per_item
        return total_price

class CartItem(models.Model):
    book = models.ForeignKey("bookview.Book", on_delete=models.PROTECT, verbose_name='book_in_cart')
    quantity = models.IntegerField(default=1, verbose_name='Quantity')
    price_ht = models.DecimalField('Price', blank=True, max_digits=5, decimal_places=2)
    cart = models.ForeignKey("cartview.Cart", on_delete=models.CASCADE, verbose_name='Cart', related_name='bookview')
    total = models.DecimalField(verbose_name='Total', max_digits=5, decimal_places=2)
    created_at = models.DateTimeField('Created At',auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField('Updated At', auto_now=True, auto_now_add=False)

    @property
    def price_per_item(self):
        return self.price_ht * int(self.quantity)

class OrderStatus(models.Model):
    TYPES_OF_STATUSES = [
        ('new', 'New Order'),
        ('in_progress', 'In Progress'),
        ('done', 'Done'),
    ]
    types_of_statuses = models.CharField(max_length=20, choices=TYPES_OF_STATUSES, default ='new',unique=True)
    def __str__(self):
        return self.types_of_statuses

class Order(models.Model):
    status = models.ForeignKey(OrderStatus, on_delete=models.PROTECT, blank=True, null=True, verbose_name='Order Status')
    cart = models.OneToOneField("cartview.Cart", on_delete=models.PROTECT, verbose_name='Cart', related_name='order')
    name_surname = models.CharField(verbose_name="First and Last Name", blank=False, max_length=40)
    address_line1 = models.CharField(verbose_name="Address Line 1", blank=False, max_length=60)
    address_line2 = models.CharField(verbose_name="Address Line 2", blank=True, max_length=60)
    town_city = models.CharField(verbose_name="Town/City", blank=False, max_length=60)
    country = models.CharField(verbose_name="Country", blank=False, max_length=60)
    phone_number = models.CharField(verbose_name="Phone Number",blank=True, max_length=60)
    email = models.EmailField(verbose_name="Email", blank=False, max_length=100)
    created_at = models.DateTimeField('Created At',auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField('Updated At', auto_now=True, auto_now_add=False)
    order_comment = models.TextField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name='Comment for Order')

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta(name='viewport', content='width=device-width, initial-scale=1')>
        <meta(name='description', content='')>
        <meta(name='author', content='')>
        <link href="{% static 'ref/bs/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'ref/bs/icon/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="{% static 'ref/bs/css/styles.css' %}" rel="stylesheet"> <!--core stylesheet-->
        <!--<link href="{% static 'ref/bs/icon/favicon.ico' %}" rel="icon" > 
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>-->
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <script src="{% static 'ref/bs/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'ref/bs/js/bootstrap.bundle.min.js' %}"></script> <!-- Bootstrap core JS-->

        <title>{% block title %}Default title{% endblock title %}</title>
    </head>
        <body>
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container px-4 px-lg-5">
                    <a class="navbar-brand" href="{% url 'main' %}">MegaReader: Online book store</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-shop-window"></i> Shop Now</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="/bookview/list_book_us/">All Products</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="/bookview/list_book_na/">New Arrivals</a></li>
                                    <li><a class="dropdown-item" href="/bookview/list_book_sl/">Goods on Sale</a></li>
                                </ul>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link active" aria-current="page" >Welcome, <i>{{ user.username }}</i></a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-circle"></i> User</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">LogOut</a></li>
                                </ul>
                            {% else %}
                            <li class="nav-item"><a class="nav-link active" aria-current="page">Welcome to the shop!</a></li><li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'loginpage:login' %}"><i> Please <b>log in.</b></i></a></li>
                            {% endif %}
                            {% if perms.contenttypes.change_contenttype %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-gear-wide-connected"></i> Admin Screens</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% if perms.auth.admin %}
                                    <li><a class="dropdown-item" href="/admin">Django Admin</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="/bookview/list_book/">Book List Management</a></li>
                                    <li><a class="dropdown-item" href="/reflib/list_aut/">Authors List Management</a></li>
                                    <li><a class="dropdown-item" href="/reflib/list_pub/">Publishers Management</a></li>
                                </ul>
                            </li>
                            {% endif %}
                            {% if perms.contenttypes.change_contenttype or perms.cartview.view_order %}
                            <li class="nav-item"><a class="nav-link active" aria-current="page" href="/cartview/my_orders/"><i class="bi bi-truck"></i> Orders</a></li>
                            {% endif %}
                            
                        </ul>
                        <form class="d-flex" action="{% url 'cartview:cart' %}" method="get">
                            <button class="btn btn-outline-dark" type="submit">
                                <i class="bi bi-cart-check"></i>
                                User Cart
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            <div class="container">
                {% block body  %} Page Body {% endblock body %}
            </div><br>
        
            <!-- Footer-->
            <footer class="py-5 bg-dark">
                <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Django Book Store 2022</p></div>
            </footer>
        <!-- Core theme JS-->
            <script src="{% static 'ref/bs/js/scripts.js' %}"></script>
        </body>
</html>