src/bookview/urls.py
from django.urls import path
from . import views
app_name = "bookview"

urlpatterns = [
    path('add_book/', views.AddBook.as_view(), name = 'add_book'),
    path('upd_book/<int:pk>/', views.UpdBook.as_view(), name = 'upd_book'),
    path('del_book/<int:pk>/', views.DelBook.as_view(), name = 'del_book'),
    path('detls_book/<int:pk>/', views.BookView.as_view(), name = 'details_book'),
    path('list_book/', views.ListBook.as_view(), name = 'list_book'),
    path('list_book_us/', views.ListBookUs.as_view(), name = 'list_book_user'),
    path('list_book_sl/', views.ListBookSl.as_view(), name = 'list_book_sale'),
    path('list_book_na/', views.ListBookNa.as_view(), name = 'list_book_new'),
]

src/cartview/urls.py
from django.urls import path

from . import views
app_name = "cartview"

# Cart Urls

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cartitem_del/<int:pk>/', views.DeleteCartItem.as_view(), name='cartitem_del'),
    path('submit_order/', views.Order.as_view(), name='submit_order'),
    path('submit_success/', views.OrderSuccess.as_view(), name='submit_success'),
    path('my_orders/', views.MyOrders.as_view(), name='my_orders'),
    path('order_upd/<int:pk>/', views.UpdOrder.as_view(), name = 'order_update'),
    #path('cart_item', views.cart_item, name='cart_item'),
    #path('cart_item', views.ViewCartItem.as_view(), name='cart_item'),
    
]

"""
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-list', views.ListCart.as_view(), name='cart_list'),
    path('cart/create/', views.CreateCart.as_view(), name='cart_create'),
    path('cart/<int:pk>/update/', views.UpdateCart.as_view(), name='cart_update'),
    path('cart/<int:pk>/delete/', views.DeleteCart.as_view(), name='cart_delete'),
]

# CartItem Urls
urlpatterns += [
    path('cartitem/', views.cart_item, name='cartitem_view'),
    #path('cartitem/', views.ViewCartItem.as_view(), name='cartitem_view'),
    #path('cartitem/<int:pk>/', views.DetailCartItem.as_view(), name='cartitem_detail'),
    path('cartitem/create/', views.CreateCartItem.as_view(), name='cartitem_create'),
    path('cartitem/<int:pk>/update/', views.UpdateCartItem.as_view(), name='cartitem_update'),
    path('cartitem/<int:pk>/delete/', views.DeleteCartItem.as_view(), name='cartitem_delete'),
]

"""

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from reflib import views
from mainpage import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainPage.as_view(), name = 'main'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('reflib/', include('reflib.urls', namespace="reflib")),
    path('bookview/', include('bookview.urls', namespace="bookview")),
    path('profiles/', include('loginpage.urls',namespace="profiles")),
    path('cartview/', include('cartview.urls', namespace="cartview")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/bookview/models.py
from django.db import models
from django.urls import reverse_lazy
from datetime import datetime
from django.contrib.auth import settings
from reflib.models import Author, Publisher, Cover, Category

class Book(models.Model):
    book_image = models.ImageField(
        verbose_name="Book Image",
        upload_to="uploads/%Y/%m/%d/"    
    )
    book_name = models.CharField(
        max_length=100,
        verbose_name='Book Name')
    book_aut = models.ForeignKey(Author, on_delete=models.PROTECT, blank=True, verbose_name='Book Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.PROTECT, blank=True, verbose_name='Publisher', default=1)
    book_annotation = models.TextField(
        max_length=500,
        blank=False,
        null=False,
        verbose_name='Annotation')
    book_cover = models.ForeignKey(Cover, on_delete=models.CASCADE, blank=True, verbose_name='Book Cover')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, verbose_name='Category')
    price_ht = models.DecimalField(verbose_name='Price of the Book', default='1.00',blank=True, max_digits=5, decimal_places=2)
    created_at = models.DateTimeField(default=datetime.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,null=True, on_delete=models.PROTECT) 
    def __str__(self):
        return self.book_name
    

    def get_absolute_url(self):
        return reverse_lazy('bookview:details_book', kwargs=({'pk': self.pk}))
    
    TVA_AMOUNT = 19.25

    def price_ttc(self):
        return self.price_ht + self.TVA_AMOUNT

    class Meta:
        ordering = ['pk']

src/bookview/forms.py
from dataclasses import field
from django import forms
from . import models


class Book(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ["book_image","book_name","book_aut","publisher","book_annotation", "book_cover", "category", "price_ht", "created_at", "created_by"]

src/bookview/views.py
from multiprocessing import context
from tkinter import Tk
import _tkinter
from turtle import update
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from . import forms
from . import models
from django.urls import reverse_lazy
from bookview.models import Book


# Create your views here.
#View list of Bookview

class ListBook(generic.ListView):
    model = models.Book
    template_name = 'bookview/booklist.html'
    paginate_by = 5
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class BookView(generic.DetailView):
    model = models.Book
    template_name = 'bookview/bookview.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['a_book'] = models.Book.objects.filter(book_image=self)
        return context

class AddBook(generic.CreateView):
    model = models.Book
    form_class = forms.Book
    template_name = 'bookview/book_add.upd.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Add'
        return context


class UpdBook(generic.UpdateView):
    model = models.Book
    form_class = forms.Book
    template_name = 'bookview/book_add.upd.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Update'
        return context

class DelBook(generic.DeleteView):
    model = models.Book
    template_name = 'bookview/book_del.html'
    success_url = reverse_lazy("bookview:list_book")

###################################################################
# USERVIEW
class ListBookUs(generic.ListView):
    model = models.Book
    template_name = 'bookview/booklist_user.html'
    paginate_by = 5
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

# USERVIEW_SALE
class ListBookSl(generic.ListView):
    model = models.Book
    template_name = 'bookview/booklist_sl.html'
    paginate_by = 5
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        category_sl = models.Category.objects.filter(types_of_categories="SL")[0]
        context['sale_list'] = models.Book.objects.filter(category_id=category_sl)
        return context

# USERVIEW_NEW_ARRIVALS
class ListBookNa(generic.ListView):
    model = models.Book
    template_name = 'bookview/booklist_na.html'
    paginate_by = 5
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        category_na = models.Category.objects.filter(types_of_categories="NA")[0]
        context['new_list'] = models.Book.objects.filter(category_id=category_na)
        return context

src/bookview/templates/bookview/book_add.upd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ operation }} Book
{% endblock title %}

        {% block body %}
        </head>
            <body>
                <h1>{{ operation }} Book</h1>
                <div class="col-lg-6">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" class="btn btn-outline-success mt-auto" value="{{ operation }}">
                        &nbsp&nbsp&nbsp&nbsp
                        <form class="d-flex" action="{% url 'bookview:list_book' %}" method="get">
                            <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                        </form>
                    </form>
                </div>
            </body>
        {% endblock body %}

src/bookview/templates/bookview/book_del.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Delete Book
{% endblock title %}
</head>
{% block body %}
<body>
    <h1>Delete Book</h1>
    Are you really want to delete the Book with <b>PK{{ object.pk }}</b> and Name <b>{{ object.pub_name }}</b>?
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-danger mt-auto" value="Press the button to Confirm">
    </form>
    <br>

                <form class="d-flex" action="{% url 'bookview:list_book' %}" method="get">
                    <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                </form>
</body>
{% endblock body %}

src/bookview/templates/bookview/booklist.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
ADMIN: All Books
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">ADMIN: List of Books</h1><br>

<div class="container">
    <form class="d-flex" action="{% url 'bookview:add_book' %}" method="get">
      <button class="btn btn-outline-warning" type="submit"></i><i class="bi bi-plus-square"></i> Add New Book</button>
    </form><br>
  <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>PK/Edit</th>
                <th>Details..</th>
                <th>Name</th>
                <th>Author</th>
                <th>Piblisher</th>
                <th>Anotation</th>
                <th>Cover</th>
                <th>Category</th>
                <th><i class="bi bi-currency-dollar"></i></th>
                <th>Created at</th>
                <th><i class="bi bi-person"></i></th>
                <th><i class="bi bi-trash"></i></th>
            </b>
          
        </tr>
    {% for obj in object_list %}

    <tr>
        <td><a href="{% url 'bookview:upd_book' pk=obj.pk %}"><button type="button" class="btn btn-outline-warning mt-auto"><b><i class="bi bi-pencil"></i>{{ obj.pk }}</button></b></button></a></td>
        <td>
            <a href = "{% url 'bookview:details_book' pk=obj.pk %}">
              <img src="{{ obj.book_image.url }}" style="width: 6rem;" />
            </a>
          </td>
        <td>{{ obj.book_name }}</td>
        <td>{{ obj.book_aut }}</td>
        <td>{{ obj.publisher }}</td>
        <td>{{ obj.book_annotation }}</td>
        <td>{{ obj.book_cover }}</td>
        <td>{{ obj.category }}</td>
        <td>{{ obj.price_ht }}$</td>
        <td>{{ obj.created_at }}</td>
        <td>{{ obj.created_by }}</td>

        <td>
          <a href="{% url 'bookview:del_book' pk=obj.pk %}"><button type="button" class="btn btn-outline-danger mt-auto"><i class="bi bi-trash"></i></button></a>
        </td>
    </tr>
    
    {% endfor %}
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>  
  </table>
    <!--
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item disabled">
            <a class="page-link">Previous</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
        </ul>
      </nav>
      -->

 </div>
 </body>
  
{% endblock body %}

src/bookview/templates/bookview/booklist_na.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
NEW Arrivals: All Books
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">List of Books: New Arrivals</h1><br>
<div class="container">

    <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>Details..</th>
                <th>Name</th>
                <th>Author</th>
                <th>Piblisher</th>
                <th>Anotation</th>
                <th>Cover</th>
                <th><i class="bi bi-currency-dollar"></i></th>
                <th><i class="bi bi-cart-plus"></i></th>
            </b>  
        </tr>
    {% for obj in new_list %}

    <tr>
        <td>
            <a href = "{% url 'bookview:details_book' pk=obj.pk %}">
              <img src="{{ obj.book_image.url }}" style="width: 6rem;" />
            </a>
          </td>
        <td>{{ obj.book_name }}</td>
        <td>{{ obj.book_aut }}</td>
        <td>{{ obj.publisher }}</td>
        <td>{{ obj.book_annotation }}</td>
        <td>{{ obj.book_cover }}</td>
        <td>{{ obj.price_ht }}$</td>
        
        <td>
          <form action="{% url 'cartview:cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success mt-auto"><i class="bi bi-cart-plus"></i></button>
            <input type="number" name="quantity" value="1" step="1" min="1" max="20">
            <input type="hidden" name="book_pk" value=" {{ obj.pk }}">
          </form>
        </td>
    </tr>
    
    {% endfor %}
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>  
  </table>
  <!--
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item disabled">
            <a class="page-link">Previous</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
        </ul>
      </nav>
      -->
 </div>   
    </form>

{% endblock body %}

src/bookview/templates/bookview/booklist_sl.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
SALE: All Books
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">Books on Sale</h1><br>
<div class="container">

    <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>Details..</th>
                <th>Name</th>
                <th>Author</th>
                <th>Piblisher</th>
                <th>Anotation</th>
                <th>Cover</th>
                <th><i class="bi bi-currency-dollar"></i></th>
                <th><i class="bi bi-cart-plus"></i></th>
            </b>  
        </tr>
    {% for obj in sale_list %}

    <tr>
          <td>
            <a href = "{% url 'bookview:details_book' pk=obj.pk %}">
              <img src="{{ obj.book_image.url }}" style="width: 6rem;" />
            </a>
          </td>
        <td>{{ obj.book_name }}</td>
        <td>{{ obj.book_aut }}</td>
        <td>{{ obj.publisher }}</td>
        <td>{{ obj.book_annotation }}</td>
        <td>{{ obj.book_cover }}</td>
        <td>{{ obj.price_ht }}$</td>
        
        <td>
          <form action="{% url 'cartview:cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success mt-auto"><i class="bi bi-cart-plus"></i></button>
            <input type="number" name="quantity" value="1" step="1" min="1" max="20">
            <input type="hidden" name="book_pk" value=" {{ obj.pk }}">
          </form>
        </td>
    </tr>
    
    {% endfor %}
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>  
  </table>
  <!--
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item disabled">
            <a class="page-link">Previous</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
        </ul>
      </nav>
      -->
 </div>   
    </form>
    
{% endblock body %}

src/bookview/templates/bookview/booklist_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
All Books
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">List of all Books</h1><br>
<div class="container">

    <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>Details..</th>
                <th>Name</th>
                <th>Author</th>
                <th>Piblisher</th>
                <th>Anotation</th>
                <th>Cover</th>
                <th><i class="bi bi-currency-dollar"></i></th>
                <th><i class="bi bi-cart-plus"></i></th>
            </b>  
        </tr>
    {% for obj in object_list %}

    <tr>
        <td>
            <a href = "{% url 'bookview:details_book' pk=obj.pk %}">
              <img src="{{ obj.book_image.url }}" style="width: 6rem;" />
            </a>
          </td>
        </td>
        <td>{{ obj.book_name }}</td>
        <td>{{ obj.book_aut }}</td>
        <td>{{ obj.publisher }}</td>
        <td>{{ obj.book_annotation }}</td>
        <td>{{ obj.book_cover }}</td>
        <td>{{ obj.price_ht }}$</td>
        
        <td>
          <form action="{% url 'cartview:cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success mt-auto"><i class="bi bi-cart-plus"></i></button>
            <input type="number" name="quantity" value="1" step="1" min="1" max="20">
            <input type="hidden" name="book_pk" value=" {{ obj.pk }}">
          </form>
        </td>
    </tr>
    
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>  
  </table>
  <!--
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item disabled">
            <a class="page-link">Previous</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
        </ul>
      </nav>
      -->
 </div>   
    </form>
{% endblock body %}

src/bookview/templates/bookview/bookview.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Details of the Book
{% endblock title %}

{% block body %}
<body>
<h2>{{ object.book_aut }}: {{ object.book_name }}</h2>
<br>
    <form class="d-flex" action="{% url 'bookview:list_book_user' %}" method="get">
      <button class="btn btn-outline-secondary" type="submit"></i><i class="bi bi-arrow-left-square"></i> Back to the List of Books</button>
    </form><br>

<div class="card mb-3" style="max-width: 1240px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ object.book_image.url }}" class="img-fluid rounded-start" alt="No Image">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">
            <b>Annotation:</b> {{ object.book_annotation }}<br>
            <b>Publisher:</b> {{ object.publisher }}<br>
            <b>Type of the book cover:</b> {{ object.book_cover }}<br>
            <b>Book category:</b> {{ object.category }}<br>
            <b>Price: </b> {{ object.price_ht }}$<br>
          </p>
          <td>
          <form action="{% url 'cartview:cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success mt-auto">Add to Cart <i class="bi bi-cart-plus"></i></button>
            <input type="number" name="quantity" value="1" step="1" min="1" max="20">
            <input type="hidden" name="book_pk" value=" {{ object.pk }}">
          </form>
        </td>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</body>

{% endblock body %}