src/cartview/urls.py
from django.urls import path

from . import views
app_name = "cartview"

# Cart Urls

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cartitem_del/<int:pk>/', views.DeleteCartItem.as_view(), name='cartitem_del'),
    path('submit_order/', views.Order.as_view(), name='submit_order'),
    path('submit_success/', views.OrderSuccess.as_view(), name='submit_success'),
    path('my_orders/', views.MyOrders.as_view(), name='my_orders'),
    path('order_upd/<int:pk>/', views.UpdOrder.as_view(), name = 'order_update'),
    #path('cart_item', views.cart_item, name='cart_item'),
    #path('cart_item', views.ViewCartItem.as_view(), name='cart_item'),
    
]

"""
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-list', views.ListCart.as_view(), name='cart_list'),
    path('cart/create/', views.CreateCart.as_view(), name='cart_create'),
    path('cart/<int:pk>/update/', views.UpdateCart.as_view(), name='cart_update'),
    path('cart/<int:pk>/delete/', views.DeleteCart.as_view(), name='cart_delete'),
]

# CartItem Urls
urlpatterns += [
    path('cartitem/', views.cart_item, name='cartitem_view'),
    #path('cartitem/', views.ViewCartItem.as_view(), name='cartitem_view'),
    #path('cartitem/<int:pk>/', views.DetailCartItem.as_view(), name='cartitem_detail'),
    path('cartitem/create/', views.CreateCartItem.as_view(), name='cartitem_create'),
    path('cartitem/<int:pk>/update/', views.UpdateCartItem.as_view(), name='cartitem_update'),
    path('cartitem/<int:pk>/delete/', views.DeleteCartItem.as_view(), name='cartitem_delete'),
]

"""

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from reflib import views
from mainpage import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainPage.as_view(), name = 'main'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('reflib/', include('reflib.urls', namespace="reflib")),
    path('bookview/', include('bookview.urls', namespace="bookview")),
    path('profiles/', include('loginpage.urls',namespace="profiles")),
    path('cartview/', include('cartview.urls', namespace="cartview")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reflib/urls.py
from django.urls import path
from . import views
app_name = "reflib"

urlpatterns = [
    path('add_aut/', views.AddAuthor.as_view(), name = 'add_author'),
    path('upd_aut/<int:pk>/', views.UpdAuthor.as_view(), name = 'upd_author'),
    path('del_aut/<int:pk>/', views.DelAuthor.as_view(), name = 'del_author'),
    path('detls_aut/<int:pk>/', views.DetailAuthor.as_view(), name = 'details_author'),
    path('list_aut/', views.ListAuthor.as_view(), name = 'list_author'),
    
    path('add_pub/', views.AddPublisher.as_view(), name = 'add_publisher'),
    path('upd_pub/<int:pk>/', views.UpdPublisher.as_view(), name = 'upd_publisher'),
    path('del_pub/<int:pk>/', views.DelPublisher.as_view(), name = 'del_publisher'),
    path('detls_pub/<int:pk>/', views.DetailPublisher.as_view(), name = 'details_publisher'),
    path('list_pub/', views.ListPublisher.as_view(), name = 'list_publisher'),
]

src/reflib/models.py
from typing import Generic
from django.db import models
from django.urls import reverse_lazy

# Create your models here.
class Publisher(models.Model):
    pub_name = models.CharField(
        max_length=100,
        verbose_name='Publisher Name',
        unique=True)
    pub_country = models.CharField(
        max_length=100,
        verbose_name='Publisher Origin')
    pub_note = models.TextField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Note')
    def get_absolute_url(self):
        return reverse_lazy('reflib:details_publisher', kwargs={'pk': self.pk})
    class Meta:
        ordering = ['pk']
    def __str__(self):
        return self.pub_name
    

class Author(models.Model):
    auth_name = models.CharField(
        max_length=100,
        verbose_name='Author Name',
        unique=True)
    auth_country = models.CharField(
        max_length=100,
        verbose_name='Author Origin')
    auth_note = models.TextField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Note')
    def get_absolute_url(self):
        return reverse_lazy('reflib:details_author', kwargs={'pk': self.pk})
    class Meta:
        ordering = ['pk']
    def __str__(self):
        return self.auth_name

class Cover(models.Model):
    HADRCOVER = 'HC'
    SOFTCOVER = 'SC'
    DUSTJACKET = 'DJ'
    TYPES_OF_COVER_CHOICES = [
        (HADRCOVER, 'Hard Cover'),
        (SOFTCOVER, 'Softcover'),
        (DUSTJACKET, 'Dust Jacket'),
    ]
    types_of_cover = models.CharField(
        max_length=2,
        choices=TYPES_OF_COVER_CHOICES,
        default=HADRCOVER,
        unique=True,
    )
    def __str__(self):
        return self.types_of_cover
    

class Category(models.Model):
    TYPES_OF_CATEGORIES = [
        ('SL', 'Sale'),
        ('NA', 'New Arrival'),
        ('NC', 'No Category'),
    ]
    types_of_categories = models.CharField(max_length=2, choices=TYPES_OF_CATEGORIES, default = 'NC',unique=True)
    def __str__(self):
        return self.types_of_categories

src/reflib/forms.py
from dataclasses import field
from django import forms

from . import models

class Author(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = ["auth_name","auth_country","auth_note"]


class Publisher(forms.ModelForm):
    class Meta:
        model = models.Publisher
        fields = ["pub_name","pub_country","pub_note"]

src/reflib/views.py
from multiprocessing import context
from turtle import update
from django.views import generic
from . import models, forms
from django.urls import reverse_lazy


# Create your views here.
#View list of Authors

class ListAuthor(generic.ListView):
    model = models.Author
    template_name = 'reflib/list_aut.html'
    paginate_by = 5
    

class DetailAuthor(generic.DetailView):
    model = models.Author
    template_name = 'reflib/details_aut.html'

class AddAuthor(generic.CreateView):
    model = models.Author
    form_class = forms.Author
    template_name = 'reflib/add.upd_aut.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Add'
        return context


class UpdAuthor(generic.UpdateView):
    model = models.Author
    form_class = forms.Author
    template_name = 'reflib/add.upd_aut.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Update'
        return context

class DelAuthor(generic.DeleteView):
    model = models.Author
    template_name = 'reflib/del_aut.html'
    success_url = reverse_lazy("reflib:list_author")



###################################################################
#View list of Publishers
class ListPublisher(generic.ListView):
    model = models.Publisher
    template_name = 'reflib/pub_list.html'
    paginate_by = 5


class DetailPublisher(generic.DetailView):
    model = models.Publisher
    template_name = 'reflib/pub_details.html'

class AddPublisher(generic.CreateView):
    model = models.Publisher
    form_class = forms.Publisher
    template_name = 'reflib/pub_add.upd.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Add'
        return context


class UpdPublisher(generic.UpdateView):
    model = models.Publisher
    form_class = forms.Publisher
    template_name = 'reflib/pub_add.upd.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Update'
        return context

class DelPublisher(generic.DeleteView):
    model = models.Publisher
    template_name = 'reflib/pub_del.html'
    success_url = reverse_lazy("reflib:list_publisher")

src/reflib/templates/reflib/add.upd_aut.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ operation }} Author
{% endblock title %}
</head>
{% block body %}
<body>
    <div class="col-lg-6">
        <h1>{{ operation }} Author</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="btn-group">
                <input type="submit" class="btn btn-outline-success mt-auto" value="{{ operation }}">
                &nbsp&nbsp&nbsp&nbsp&nbsp
                <form class="d-flex" action="{% url 'reflib:list_author' %}" method="get">
                    <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                </form>
            </div>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</body>
{% endblock body %}

src/reflib/templates/reflib/del_aut.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Delete Author
{% endblock title %}

{% block body %}
<body>
    <h1>Delete</h1>
    Are you really want to delete the Author with <b>PK{{ object.pk }}</b> and Name <b>{{ object.auth_name }}</b>?
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-danger mt-auto" value="Press the button to Confirm">
    </form>
    <br>

                <form class="d-flex" action="{% url 'reflib:list_author' %}" method="get">
                    <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                </form>
</body>
{% endblock body %}

src/reflib/templates/reflib/details_aut.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Author Details
{% endblock title %}

{% block body %}
<body>
    
    <h1>{{ object.auth_name }}</h1>
    <br>
    <div class="btn-group">
        <form class="d-flex" action="{% url 'reflib:list_author' %}" method="get">
        <button class="btn btn-outline-secondary" type="submit"></i><i class="bi bi-arrow-left-square"></i> Back to the List of Authors</button>
        </form>&nbsp&nbsp&nbsp&nbsp&nbsp
        <form class="d-flex" action="{% url 'reflib:upd_author' pk=object.pk %}" method="get">
        <button class="btn btn-outline-warning" type="submit"></i><i class="bi bi-pencil"></i> Edit</button>
        </form>
    </div>
    <br>
    <br>

<div class="card mb-3" style="max-width: 700px;">
    <div class="row g-0">
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">
            <b>PK:</b> {{ object.pk }}<br>
            <b>NOTE:</b> {{ object.auth_note }}<br>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </p>
        </div>
       </div>  
    </div>  
</div>  
</body>

{% endblock body %}

src/reflib/templates/reflib/list_aut.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
All Authors
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">List of Authors</h1><br>
<div class="container">
    <form class="d-flex" action="{% url 'reflib:add_author' %}" method="get">
      <button class="btn btn-outline-warning" type="submit"></i><i class="bi bi-plus-square"></i> Add new Author</button>
    </form><br>
    <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>PK</th>
                <th>Author</th>
                <th>Origination</th>
                <th>Note</th>
                <th><i class="bi bi-trash"></th>
            </b>
          
        </tr>
    {% for obj in object_list %}

    <tr>
        <td><a href="{% url 'reflib:upd_author' pk=obj.pk %}"><button type="button" class="btn btn-outline-warning mt-auto"><b><i class="bi bi-pencil"></i>{{ obj.pk }}</b></button></a></td>
        <td><a href="{% url 'reflib:details_author' pk=obj.pk %}">{{ obj.auth_name }}</a></td>
        <td>{{ obj.auth_country }}</td>
        <td>{{ obj.auth_note }}</td>
        <td><a href="{% url 'reflib:del_author' pk=obj.pk %}"><button type="button" class="btn btn-outline-danger mt-auto"><i class="bi bi-trash"></i></button></a></td>
    </tr>
    
    {% endfor %}
    
<div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                
          </div>  
  </table>
</div>   
</body>
{% endblock body %}

src/reflib/templates/reflib/pub_add.upd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ operation }} Publisher
{% endblock title %}
</head>
{% block body %}
<body>
    <div class="col-lg-6">
        <h1>{{ operation }} Publisher</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="btn-group">
                <input type="submit" class="btn btn-outline-success mt-auto" value="{{ operation }}">
                &nbsp&nbsp&nbsp&nbsp&nbsp
                <form class="d-flex" action="{% url 'reflib:list_publisher' %}" method="get">
                    <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                </form>
            </div>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</body>
{% endblock body %}

src/reflib/templates/reflib/pub_del.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Delete Publisher
{% endblock title %}
</head>
{% block body %}
<body>
    <h1>Delete</h1>
    Are you really want to delete the Publisher with <b>PK{{ object.pk }}</b> and Name <b>{{ object.pub_name }}</b>?
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-danger mt-auto" value="Press the button to Confirm">
    </form>
    <br>

                <form class="d-flex" action="{% url 'reflib:list_publisher' %}" method="get">
                    <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                </form>
</body>
{% endblock body %}

src/reflib/templates/reflib/pub_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Publisher Details
{% endblock title %}

{% block body %}
<h1>{{ object.pub_name }}</h1>
    <br>
    <div class="btn-group">
        <form class="d-flex" action="{% url 'reflib:list_publisher' %}" method="get">
        <button class="btn btn-outline-secondary" type="submit"></i><i class="bi bi-arrow-left-square"></i> Back to the List of Publishers</button>
        </form>&nbsp&nbsp&nbsp&nbsp&nbsp
        <form class="d-flex" action="{% url 'reflib:upd_publisher' pk=object.pk %}" method="get">
        <button class="btn btn-outline-warning" type="submit"></i><i class="bi bi-pencil"></i> Edit</button>
        </form>
    </div>
    <br>
    <br>

<div class="card mb-3" style="max-width: 700px;">
    <div class="row g-0">
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">
            <b>PK:</b> {{ object.pk }}<br>
            <b>NOTE:</b> {{ object.pub_note }}<br>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </p>
        </div>
       </div>  
    </div>  
</div>  


{% endblock body %}

src/reflib/templates/reflib/pub_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
All Publishers
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">List of Publishers</h1><br>
<div class="container">
    <form class="d-flex" action="{% url 'reflib:add_publisher' %}" method="get">
      <button class="btn btn-outline-warning" type="submit"></i><i class="bi bi-plus-square"></i> Add New Publisher</button>
    </form><br>
    <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>PK</th>
                <th>Publisher Name</th>
                <th>Publisher Origin</th>
                <th>Note</th>
                <th><i class="bi bi-trash"></th>
            </b>
          
        </tr>
    {% for obj in object_list %}

    <tr>
        <td><a href="{% url 'reflib:upd_publisher' pk=obj.pk %}"><button type="button" class="btn btn-outline-warning mt-auto"><b><i class="bi bi-pencil"></i>{{ obj.pk }}</b></button></a></td>
        <td><a href="{% url 'reflib:details_publisher' pk=obj.pk %}">{{ obj.pub_name }}</a></td>
        <td>{{ obj.pub_country }}</td>
        <td>{{ obj.pub_note }}</td>
        <td><a href="{% url 'reflib:del_publisher' pk=obj.pk %}"><button type="button" class="btn btn-outline-danger mt-auto"><i class="bi bi-trash"></i></button></a></td>
    </tr>
    
    {% endfor %}
   
<div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                
          </div>  
  </table>
</div>   
</body>
{% endblock body %}