src/bookview/urls.py
from django.urls import path
from . import views
app_name = "bookview"

urlpatterns = [
    path('add_book/', views.AddBook.as_view(), name = 'add_book'),
    path('upd_book/<int:pk>/', views.UpdBook.as_view(), name = 'upd_book'),
    path('del_book/<int:pk>/', views.DelBook.as_view(), name = 'del_book'),
    path('detls_book/<int:pk>/', views.BookView.as_view(), name = 'details_book'),
    path('list_book/', views.ListBook.as_view(), name = 'list_book'),
    path('list_book_us/', views.ListBookUs.as_view(), name = 'list_book_user'),
    path('list_book_sl/', views.ListBookSl.as_view(), name = 'list_book_sale'),
    path('list_book_na/', views.ListBookNa.as_view(), name = 'list_book_new'),
]

src/cartview/urls.py
from django.urls import path

from . import views
app_name = "cartview"

# Cart Urls

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cartitem_del/<int:pk>/', views.DeleteCartItem.as_view(), name='cartitem_del'),
    path('submit_order/', views.Order.as_view(), name='submit_order'),
    path('submit_success/', views.OrderSuccess.as_view(), name='submit_success'),
    path('my_orders/', views.MyOrders.as_view(), name='my_orders'),
    path('order_upd/<int:pk>/', views.UpdOrder.as_view(), name = 'order_update'),
    #path('cart_item', views.cart_item, name='cart_item'),
    #path('cart_item', views.ViewCartItem.as_view(), name='cart_item'),
    
]

"""
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-list', views.ListCart.as_view(), name='cart_list'),
    path('cart/create/', views.CreateCart.as_view(), name='cart_create'),
    path('cart/<int:pk>/update/', views.UpdateCart.as_view(), name='cart_update'),
    path('cart/<int:pk>/delete/', views.DeleteCart.as_view(), name='cart_delete'),
]

# CartItem Urls
urlpatterns += [
    path('cartitem/', views.cart_item, name='cartitem_view'),
    #path('cartitem/', views.ViewCartItem.as_view(), name='cartitem_view'),
    #path('cartitem/<int:pk>/', views.DetailCartItem.as_view(), name='cartitem_detail'),
    path('cartitem/create/', views.CreateCartItem.as_view(), name='cartitem_create'),
    path('cartitem/<int:pk>/update/', views.UpdateCartItem.as_view(), name='cartitem_update'),
    path('cartitem/<int:pk>/delete/', views.DeleteCartItem.as_view(), name='cartitem_delete'),
]

"""

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from reflib import views
from mainpage import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainPage.as_view(), name = 'main'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('reflib/', include('reflib.urls', namespace="reflib")),
    path('bookview/', include('bookview.urls', namespace="bookview")),
    path('profiles/', include('loginpage.urls',namespace="profiles")),
    path('cartview/', include('cartview.urls', namespace="cartview")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cartview/models.py
from django.db import models
from django.contrib.auth import get_user_model
from bookview.models import Book


User = get_user_model()
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="carts", verbose_name="User Cart", null=True,blank=True)
    created_at = models.DateTimeField('Created At',auto_now=False, auto_now_add=True
    )
    
   
    def total_price(self):
        all_items_in_cart = self.bookview.all()
        total_price = 0
        for item_in_cart in all_items_in_cart:
            total_price += item_in_cart.price_per_item
        return total_price

class CartItem(models.Model):
    book = models.ForeignKey("bookview.Book", on_delete=models.PROTECT, verbose_name='book_in_cart')
    quantity = models.IntegerField(default=1, verbose_name='Quantity')
    price_ht = models.DecimalField('Price', blank=True, max_digits=5, decimal_places=2)
    cart = models.ForeignKey("cartview.Cart", on_delete=models.CASCADE, verbose_name='Cart', related_name='bookview')
    total = models.DecimalField(verbose_name='Total', max_digits=5, decimal_places=2)
    created_at = models.DateTimeField('Created At',auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField('Updated At', auto_now=True, auto_now_add=False)

    @property
    def price_per_item(self):
        return self.price_ht * int(self.quantity)

class OrderStatus(models.Model):
    TYPES_OF_STATUSES = [
        ('new', 'New Order'),
        ('in_progress', 'In Progress'),
        ('done', 'Done'),
    ]
    types_of_statuses = models.CharField(max_length=20, choices=TYPES_OF_STATUSES, default ='new',unique=True)
    def __str__(self):
        return self.types_of_statuses

class Order(models.Model):
    status = models.ForeignKey(OrderStatus, on_delete=models.PROTECT, blank=True, null=True, verbose_name='Order Status')
    cart = models.OneToOneField("cartview.Cart", on_delete=models.PROTECT, verbose_name='Cart', related_name='order')
    name_surname = models.CharField(verbose_name="First and Last Name", blank=False, max_length=40)
    address_line1 = models.CharField(verbose_name="Address Line 1", blank=False, max_length=60)
    address_line2 = models.CharField(verbose_name="Address Line 2", blank=True, max_length=60)
    town_city = models.CharField(verbose_name="Town/City", blank=False, max_length=60)
    country = models.CharField(verbose_name="Country", blank=False, max_length=60)
    phone_number = models.CharField(verbose_name="Phone Number",blank=True, max_length=60)
    email = models.EmailField(verbose_name="Email", blank=False, max_length=100)
    created_at = models.DateTimeField('Created At',auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField('Updated At', auto_now=True, auto_now_add=False)
    order_comment = models.TextField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name='Comment for Order')

src/cartview/forms.py
from dataclasses import field
from django import forms
from . import models


class Cart(forms.ModelForm):
    class Meta:
        model = models.Cart
        fields = ["user"]

class CartItem(forms.ModelForm):
    class Meta:
        model = models.CartItem
        fields = ["book","quantity","price_ht","cart"]


class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ["name_surname","address_line1","address_line2","town_city","country","phone_number","email"]

class MyOrders(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ["name_surname","address_line1","address_line2","town_city","country","phone_number","email"]
class EditOrders(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ["status","name_surname","address_line1","address_line2","town_city","country","phone_number","email", "order_comment"]
        

src/cartview/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from cartview import models, forms
from . forms import OrderForm
from . models import Cart, CartItem
from bookview import models as bw_models
from random import randint
from django.urls import reverse_lazy
from cartview.models import Order as OrderModel, Cart as CartModel

class DeleteCartItem(DeleteView):
    model = models.CartItem
    success_url = reverse_lazy("cartview:cart")
    template_name = 'cartview/cartitem_delete.html'


def cart(request, *args, **kwargs):
    context = {}
    context['cart'] = None
    if request.method == "POST":
        book_pk = request.POST.get('book_pk')
        quantity = request.POST.get('quantity')
        if book_pk and quantity:
            cart_id = int(request.session.get('cart_id',0))
            if request.user.is_authenticated:
                user = request.user
            else:
                user = None
            if cart_id == 0:
                cart_id = None
            cart, created = models.Cart.objects.get_or_create(
                pk=cart_id,
                defaults={"user": user}
            )
            context["cart"] = cart
            if created:
                request.session['cart_id'] = cart.pk
            book = bw_models.Book.objects.get(pk=int(book_pk))
            obj = bw_models.Book.objects.get(pk=int(book_pk))
            obj_price = int(obj.price_ht)
            books_in_cart, created = models.CartItem.objects.get_or_create(
                book=book,
                cart=cart,
                total=obj_price*int(quantity),
                defaults={
                    "quantity":quantity,
                    "price_ht":obj_price,
                    }
            )
            if not created: ##bug - sometimes on attempt to add the same item - duplicaiton of recorsds, selection of 3 records instead of 1
                books_in_cart.quantity = books_in_cart.quantity + int(quantity)
                books_in_cart.total = obj_price * int(books_in_cart.quantity)
                books_in_cart.save()
    else:
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart = models.Cart.objects.get(pk=cart_id)
            context['cart'] = cart
    context['form'] = forms.OrderForm
    return render(
        request,
        template_name='cartview/cart.html',
        context = context
        )
##-------------- CartItem Views --------------------------------------

class Order(CreateView):
    template_name = "cartview/submit_order.html"
    models = models.Order
    form_class = forms.OrderForm
    success_url = reverse_lazy("cartview:submit_success")
    def form_valid(self, form):
        cart = models.Cart.objects.get(pk=self.request.session.get('cart_id'))
        form.instance.cart = cart
        obj = models.OrderStatus.objects.get(types_of_statuses__contains='new')
        form.instance.status = obj
        return super().form_valid(form)
         
    def get_success_url(self) -> str:
        del self.request.session["cart_id"]
        return super().get_success_url()

class OrderSuccess(TemplateView):
    model = models.Order
    template_name = "cartview/submit_success.html"
    
class MyOrders(ListView):
    template_name = "cartview/my_orders.html"
    model = models.Order
    form_class = forms.MyOrders
    paginate_by = 10
    
    """
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        #context['all_orders'] = models.Order.objects.get()[:0]
        #context['user_orders'] = bw_models.Book.objects.filter(category_id="2").order_by('-created_at')
        return context
        
    """
    def get_context_data(self, *args, **kwargs):
        order_list = ''

        if self.request.user.is_authenticated:
            if self.request.user.has_perm("auth.admin") or \
                self.request.user.has_perm("contenttypes.change_contenttype"):
                order_list = models.Order.objects.all().order_by("status", "-created_at")
            elif self.request.user.has_perm("cartview.view_order"):
                cur_user = self.request.user
                cart_list = CartModel.objects.all().filter(user_id=cur_user).values('pk')
                order_list = models.Order.objects.all().filter(cart_id=cart_list).order_by("-created_at")
        context = super().get_context_data(object_list=order_list, *args, **kwargs)
        return context


class UpdOrder(generic.UpdateView):
    model = models.Order
    form_class = forms.EditOrders
    template_name = 'cartview/order_add.upd.html'
    success_url = reverse_lazy("cartview:my_orders")
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation'] = 'Update'
        return context

src/cartview/templates/cartview/cart_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Cart
{% endblock title %}

{% block body %}
<body>
    <h1>Cart</h1>
    <b>PK{{ object.pk }}</b><br>
    <b>{{ object.book_image }}</b><br>
    <b>Name of the Book{{ object.book_name }}</b><br>
    <b>Author{{ object.book_name }}</b><br>
    <b>Type of the book cover{{ object.book_cover }}</b><br>

</body>
{% endblock body %}

src/cartview/templates/cartview/cart_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Delete Cart
{% endblock title %}
</head>
{% block body %}
<body>
    <h1>Delete Cart</h1>
    Are you really want to delete the Cart with <b>PK{{ object.pk }}</b> and User Name <b>{{ object.user }}</b> created {{ object.created_at }}</b>?
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Press the button to Confirm">
    </form>
</body>
{% endblock body %}

src/cartview/templates/cartview/cart_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
List of carts
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">List of all carts</b></h1><br>
<div class="container">

    <table class="table table-striped table-hover">
        <tr>
           <b>
              <th>PK</th>
              <th>User</th>
              <th>Created at</th>
              <th>Delete?</th>
            </b>
          </tr>
        {% for obj in object_list %}

      <tr>
          <td>{{ obj.pk }}</td>
          <td>{{ obj.user }}</td>
          <td>{{ obj.created_at }}</td>
          <td>{{ obj.created_at }}</td>
          <td><a href="{% url 'cartview:cart_delete' pk=obj.pk %}"><button type="button" class="btn btn-danger"><b>Delete<i class="bi bi-x-lg"></i></b></button></a></td>
      </tr>
      
      {% endfor %}
    </table>
    
{% endblock body %}

src/cartview/templates/cartview/cart_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ operation }} Cart
{% endblock title %}

        {% block body %}
        </head>
            <body>
                <h1>{{ operation }} Cart</h1>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-success" value="{{ operation }}">


                </form>
            </body>
        {% endblock body %}

src/cartview/templates/cartview/cartitem.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Cart
{% endblock title %}

{% block body %}


</body>
{% endblock body %}

src/cartview/templates/cartview/cartitem_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Cart
{% endblock title %}

{% block body %}
<body>
    <h1>Cart</h1>
    <b>PK{{ object.pk }}</b><br>
    <b>{{ object.book_image }}</b><br>
    <b>Name of the Book{{ object.book_name }}</b><br>
    <b>Author{{ object.book_name }}</b><br>
    <b>Type of the book cover{{ object.book_cover }}</b><br>

</body>
{% endblock body %}

src/cartview/templates/cartview/cartitem_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Delete Position
{% endblock title %}
</head>
{% block body %}
<body>
    <h1>Delete Position?</h1>
    Are you really want to delete the Item with <b>PK{{ object.pk }}</b> and Name <b>{{ object.book }}</b>?
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-danger mt-auto">Press the button to Confirm</button>
    </form>
</body>
{% endblock body %}

src/cartview/templates/cartview/cartitem_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Cart
{% endblock title %}

{% block body %}


</body>
{% endblock body %}

src/cartview/templates/cartview/cartitems_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Cart
{% endblock title %}

{% block body %}
<body>
    <h1>Cart</h1>
    <b>PK{{ object.pk }}</b><br>
    <b>{{ object.book_image }}</b><br>
    <b>Name of the Book{{ object.book_name }}</b><br>
    <b>Author{{ object.book_name }}</b><br>
    <b>Type of the book cover{{ object.book_cover }}</b><br>

</body>
{% endblock body %}

src/cartview/templates/cartview/my_orders.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
My Orders
{% endblock title %}

{% block body %}
</head>
<body>
    <h1 style ="text-align:center;">My Orders</h1><br>
<div class="container">
    <table class="table table-striped table-hover">
        <tr>
            <b>
                <th>Order ID</th>
                <th>Order Details</th>
                <th>Order Status</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Comment</th>
            </b>
          
        </tr>
    {% for obj in object_list %}

    <tr>
        <td><a href="{% url 'cartview:order_update' pk=obj.pk %}"><button type="button" class="btn btn-outline-warning mt-auto"><b><i class="bi bi-pencil"></i>{{ obj.pk }}</b></button></a></td>
        <td>{{ obj.cart}}</td>
        <td>{{ obj.status }}</td>
        <td>{{ obj.created_at }}</td>
        <td>{{ obj.updated_at }}</td>
        <td>{{ obj.order_comment }}</td>
    </tr>
    
    {% endfor %}
   
<div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                
          </div>  
  </table>
</div>   
</body>
{% endblock body %}

src/cartview/templates/cartview/order_add.upd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ operation }} Order
{% endblock title %}
</head>
{% block body %}
<body>
    <div class="col-lg-6">
        <h1>{{ operation }} Order</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="btn-group">
                <input type="submit" class="btn btn-outline-success mt-auto" value="{{ operation }}">
                &nbsp&nbsp&nbsp&nbsp&nbsp
                <form class="d-flex" action="{% url 'cartview:my_orders' %}" method="get">
                    <button class="btn btn-outline-secondary" type="submit"> Cancel </button>
                </form>
            </div>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</body>
{% endblock body %}

src/cartview/templates/cartview/orderdeails.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Details of the Book
{% endblock title %}

{% block body %}
<body>
<h2>{{ object.book_aut }}: {{ object.book_name }}</h2>
<br>
    <form class="d-flex" action="{% url 'bookview:list_book_user' %}" method="get">
      <button class="btn btn-outline-secondary" type="submit"></i><i class="bi bi-arrow-left-square"></i> Back to the List of Books</button>
    </form><br>

<div class="card mb-3" style="max-width: 1240px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ object.book_image.url }}" class="img-fluid rounded-start" alt="No Image">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">
            <b>Annotation:</b> {{ object.book_annotation }}<br>
            <b>Publisher:</b> {{ object.publisher }}<br>
            <b>Type of the book cover:</b> {{ object.book_cover }}<br>
            <b>Book category:</b> {{ object.category }}<br>
            <b>Price: </b> {{ object.price_ht }}$<br>
          </p>
          <td>
          <form action="{% url 'cartview:cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success mt-auto">Add to Cart <i class="bi bi-cart-plus"></i></button>
            <input type="number" name="quantity" value="1" step="1" min="1" max="20">
            <input type="hidden" name="book_pk" value=" {{ object.pk }}">
          </form>
        </td>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</body>

{% endblock body %}

src/cartview/templates/cartview/submit_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Cart
{% endblock title %}

{% block body %}
<body>
    <h1>Cart</h1>
    <b>PK{{ object.pk }}</b><br>
    <b>{{ object.book_image }}</b><br>
    <b>Name of the Book{{ object.book_name }}</b><br>
    <b>Author{{ object.book_name }}</b><br>
    <b>Type of the book cover{{ object.book_cover }}</b><br>

</body>
{% endblock body %}

src/cartview/templates/cartview/submit_success.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Order success
{% endblock title %}

{% block body %}
    <h1> Your order was placed successfully!</h1>
    We will keep you posted about processing and delivery progress
    <div class="card mb-3" style="max-width: 1240px;">
        <div class="row g-0">
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </body>
{% endblock body %}